### ISSUE TITLE
Login with Google always returns code 1

### ISSUE THREAD

**Issue by shripalsoni04** [mkloubert/nativescript-social-login#1]
First of all, 👍  for this useful plugin.

This plugin is working perfectly fine for facebook. But, when I configured it for login with google, it always returns code 1 and no other information.

Sample Code:

``` typescript
initSocialLogin(){
        console.log('initi social login called === =');
        var result = SocialLogin.init({
            google:{
                serverClientId: "xxxx.apps.googleusercontent.com"
            }
        });
    }

loginViaGoogle(){
     SocialLogin.loginWithGoogle((result) => {
                console.log('login using google successful ', result.authToken, result.code);
     });
}
```

I have also tried to run demo application with my googleServerClientId, but there also I am getting authToken as blank and result.code as 1.

It will be great if you can help me out from this issue.

**Comment by mkloubert** [comment]
If you do not need the server client ID, you should not set the `googe.serverClientId` property.

Otherwise...

This value is the same as the first argument for [requestServerAuthCode](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#public-methods) method of [GoogleSignInOptions.Builder](GoogleSignInOptions.Builder) class.

The way how to use such a server client ID for your Android app is described in the [Enabling Server-Side Access](https://developers.google.com/identity/sign-in/android/offline-access) by Google.

But, I have the same problem:

I have a backend that should receive that `result.authToken` to verify the user, but I have no idea how to register the backend application (and my App) in the [Google Developer Console](https://console.developers.google.com/apis/library). I always get the same response code :-(

Please let me know when you are able to use this feature!

**Comment by shripalsoni04** [comment]
I got this thing working now.

There are two things to take in consideration:

1. In serverClientId, we need to pass **Web Application** type client id, which you can get it from https://console.developers.google.com/apis/credentials.

2. There are two tokens which google signIn api can provide.

-  **idToken**: This is a jwt token which contains all the basic information of the user and we can send this token to the server and server can get payload from this jwt.

- **serverAuthCode**: This is an authCode for offline use. By using this authCode server can request for idToken or refresh idToken and get the user information.

I think we should set idToken by default in `authToken` property of result object.

I have done these changes and added extra configuration `isRequestAuthCode`.  So if it is true, then `authCode` will be there in result, else `authToken` will be there in result.

You can find the code difference here: https://github.com/shripalsoni04/nativescript-social-login/commit/a18907f6ada3e217774e0ecf5728182ed3e4fa60

If you find it proper, it will be great if you can accommodate these changes in the plugin.

**Comment by mkloubert** [comment]
Great! 👍

I applied your changes, but only made `isRequestAuthCode` property optional and set its default value to `(true)` as you can here: https://github.com/mkloubert/nativescript-social-login/commit/4b1946775da585bfea4d01c6dadfe2e58b0278bc

I made this because you can work without the `serverAuthCode` property and fetch the profile information only. In this case you do not need to set the `isRequestAuthCode` property and the default value should fit with the behavior of the previous versions of the plugin.

**The new version is 1.2.0.**

**Comment by shripalsoni04** [comment]
Thanks for integrating the changes very quickly. 👍 

I think we should keep default value of `isRequestAuthCode` as `false` instead of `true`. Because,  if we keep `isRequestAuthCode` to true, its value will be set in `authCode`, but in other integrations like facebook or twitter, we are setting token in `authToken` property. So when user has multiple social login integrations, they need to handle this separately.

Also, I think by default fetching `idToken` instead of `serverAuthCode` will be more useful to the users if they directly want to call other google apis without bringing server into interaction. This will also be consistent with other integrations, where we can directly use the `authToken` to call other api of that platforms.

What do you think?

**Comment by mkloubert** [comment]
I changed the behavior in 1.3.1.

I also think that this is the better choise.

**Comment by mkloubert** [comment]
I think you have generated a `google-services.json` for your app.

If so: How can you include this into a NativeScript project?

**Comment by shripalsoni04** [comment]
Thanks for implementing the change. 

I am not using `google-services.json` as for signIn only functionality, it is not needed. 

I am not sure, but I think dropping that `google-services.json` file in `app/App_Resources/Android` folder should work.

**Comment by mkloubert** [comment]
I don't get this thing to work.

Can you explain step by step what you did?

I generated the credentials for my app:

![nativescript_sli_ss_1](https://cloud.githubusercontent.com/assets/4951215/15957690/fea6f422-2ef0-11e6-86ab-e85a90566968.jpg)

I put my SHA-1 fingerprint (DEBUG) and package name here:

![nativescript_sli_ss_2](https://cloud.githubusercontent.com/assets/4951215/15957689/fea4d5de-2ef0-11e6-9745-439df379c9f4.jpg)

I used

`keytool -list -printcert -jarfile my-app.apk`

to get the fingerprint and `AndroidManifest.xml` from the `platforms/android` folder for the package name.

I implemented the following code and used the name ID from the red box of the screenshot:

```typescript
var result = SocialLogin.init({
    google:{
        serverClientId: "xyz.apps.googleusercontent.com",
        isRequestAuthCode: false,
    }
});
```

But I always get result code `1`.

Is there something I forgot to do?

**Comment by shripalsoni04** [comment]
You need to set **webanwendung** (Web Application) type clientID and **not Android** type clientID in `serverClientId` field.

**Comment by harsh4once** [comment]
Hi,
Thanks for the plug-in, but even though after following all the steps mentioned above, still facing issue for google, it always returns result code as 1. Facebook login is working fine.

**Comment by mkloubert** [comment]
@harsh4once I currently have the same problem. I can load profile information without using the server/client ID, but the time I start defining my client ID as described above, I also get the result code 1.

Seems to be that something is still missing when building and deploying the apps.

I hope that @shripalsoni04 can help.

**Comment by shripalsoni04** [comment]
Well, I had only one issue, I was using **Android** type client id instead of **Web Application** type client id.

Check below screenshot:
![image](https://cloud.githubusercontent.com/assets/4411891/16095066/a7545a10-3360-11e6-9c2c-28b60d65f751.png)


@harsh4once  @mkloubert As per the screenshot above, can you please confirm that you are using **Web Application** type clientId and **not Android** type client id received from https://console.developers.google.com/apis/credentials for `serverClientId` field:

```
SocialLogin.init({
            google:{
                serverClientId: <WEB_APPLICATION_CLIENTID>.apps.googleusercontent.com"
            }
        });
```

**Comment by harsh4once** [comment]
Hi shripalsoni04,

I per your input, I only used the web application type client id instead of android type, but still getting same issue. Your help is really appreciated. Thanks

**Comment by votiakov** [comment]
Hi!

Is this still an issue? 
I can check this today if you still have this problem

**Comment by danieloprado** [comment]
Same problem as @harsh4once

**Comment by danieloprado** [comment]
Any update?

**Comment by pamontep** [comment]
I also got on this issue. T^T

**Comment by danieloprado** [comment]
Keep trying... 😢

**Comment by danieloprado** [comment]
I did it!

When you run: **tns run build**, tns sign the app with the **~/.android/debug.keystore**
You need to add the SHA1 of this key in you google console developer:

![screenshot from 2017-03-24 10-56-11](https://cloud.githubusercontent.com/assets/7683575/24297210/b0c795e6-1080-11e7-862c-090d3062ee9f.png)

Create a Client Android for Debug:
![screenshot from 2017-03-24 11-00-43](https://cloud.githubusercontent.com/assets/7683575/24297348/361aee96-1081-11e7-8425-2d5091a86c4a.png)

and Poof! :tada: :smile: :+1: :tada:

**Comment by jorgerb79** [comment]
Hi danieloprado, I followed your steps above and I'm still getting code 1 with empty information. Did you configure something else in Google Developer Console ?

**Comment by mrubkey** [comment]
@jorgerb79 
Important thing!
1. Your emulator need install Google Play Services. If no return code 1.
2. To get Auth Token
Set Web Application Client ID 
google: {
                serverClientId: "<YOU_CLIENT_ID>.apps.googleusercontent.com"
            }

**Comment by maniacube** [comment]
Same issue for me only on Android. And I have tried all the steps above but still getting same issue

**Comment by mrubkey** [comment]
@maniacube check my comment with step 2

**Comment by maniacube** [comment]
@mrubkey i followed your comment and Android OAuth Client created in Google Developer Console but still getting same issue

**Comment by junzou1992** [comment]
@maniacube , if you want to run on android, do a tns run android with --release --keyStorePath

**Comment by vascokk** [comment]
Hi guys,
I'm new to NS (and the JS-based front-end development as a whole). Anyway, I cannot make Google authentication work with this plugin. Here is what I've done:
1. Created Android client ID
2. added the SHA1 fingerprint
3. Set the package name according to the nativescript.id in package.json in my project root 
4. SocialLogin init: 
```javascript
        var result = SocialLogin.init({
            google:{
                serverClientId: "<android client ID>.apps.googleusercontent.com"
            },
            activity: activity
        });
```
5. Google Play services is installed:
```
 let isAvailable = com.google.android.gms.common.GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(Application.android.context);
```
returns 0 (SUCCESS)
6. Starting the app with:
`tns run android --emulator --key-store-path ~/.android/keystore/debug.keystore.jks --key-store-password <password> --key-store-alias debug --key-store-alias-password <password>`

.....and still getting result.code = 1  :(

Here is the console log:
```
Successfully synced application org.nativescript.nails on device emulator-5554.

JS: [nativescript-social-login]: (initEnvironment()): initialize.google: true
JS: [nativescript-social-login]: (initEnvironment()): initialize.facebook: true
JS: [nativescript-social-login]: (initEnvironment()): initialize.twitter: false
JS: [nativescript-social-login]: (initEnvironment()): activity: com.tns.NativeScriptActivity@e4e7116
JS: [nativescript-social-login]: (initEnvironment()): google.isInitialized: true
JS: [nativescript-social-login]: (initEnvironment()): facebook.isInitialized: true
JS: [nativescript-social-login]: (initEnvironment()): twitter.isInitialized: undefined
JS: Facebook isInitialized? true
JS: Google isInitialized? true
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ----> Play service enabled: 0
JS: [nativescript-social-login]: (undefined): Provider: google
JS: [nativescript-social-login]: (undefined): Will use Google sign in...
JS: [nativescript-social-login]: (loginWithGoogle()): Will request ID token
JS: [nativescript-social-login]: (loginWithGoogle()): Starting activity for result...
JS: [nativescript-social-login]: (initEnvironment()): initialize.google: true
JS: [nativescript-social-login]: (initEnvironment()): initialize.facebook: true
JS: [nativescript-social-login]: (initEnvironment()): initialize.twitter: false
JS: [nativescript-social-login]: (initEnvironment()): activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity@606aab6
JS: [nativescript-social-login]: (initEnvironment()): google.isInitialized: true
JS: [nativescript-social-login]: (initEnvironment()): facebook.isInitialized: true
JS: [nativescript-social-login]: (initEnvironment()): twitter.isInitialized: undefined
JS: Facebook isInitialized? true
JS: Google isInitialized? true
JS: [nativescript-social-login]: (onActivityResult()): Cancelled
JS: [nativescript-social-login]: (onActivityResult()): result.provider = google
JS: [nativescript-social-login]: (onActivityResult()): result.code = 1
JS: code: 1
JS: error: undefined
JS: userToken: undefined
JS: displayName: undefined
JS: photo: undefined
JS: authToken: undefined
```
I'd appreciate your help!

**Comment by junzou1992** [comment]
@vascokk you have to use web application client ID instead of android client ID for android.

**Comment by bradmartin** [comment]
@danieloprado - thank you for your comment. I struggled with this for a few hours.  🍻 to you 😄

**Comment by danieloprado** [comment]
@vascokk tns ignores **--key-store-path** without **--release**

**Comment by bradmartin** [comment]
Added detailed instructions which should help several who can't get this working with debug builds: https://github.com/mkloubert/nativescript-social-login/pull/14

**Comment by mkloubert** [comment]
@bradmartin 

**Thank you very much! I released the new README with version 1.5.3.**

**Comment by AmineMx** [comment]
is any one find a solution of this problems ?

**Comment by Kevvix** [comment]
Hi,

I have the same issue.
The FB part works but not the Google one.
I readded and followed carefully all steps and I still got "Code : 1" and all others values in the result are undefined.

I work on Android, I don't have IOS system.
Would you like I publish on GitHub my code?

Thank you

**Comment by andrea-spotsoftware** [comment]
@mkloubert i think i'm missing some steps. 
Why it works correctly setting up a web application clientId and it's not working (return code: 1) with android client id, without setting up a secret? 
I am confused

**Comment by AhmedAdelAtta** [comment]
> Great! 👍
> 
> I applied your changes, but only made `isRequestAuthCode` property optional and set its default value to `(true)` as you can here: [4b19467](https://github.com/mkloubert/nativescript-social-login/commit/4b1946775da585bfea4d01c6dadfe2e58b0278bc)
> 
> I made this because you can work without the `serverAuthCode` property and fetch the profile information only. In this case you do not need to set the `isRequestAuthCode` property and the default value should fit with the behavior of the previous versions of the plugin.
> 
> **The new version is 1.2.1.**

please help man, i did everything as instructed and still i get:
Calling Callback function with Results
JS: {
JS:   "provider": "google",
JS:   "code": 1
JS: }

with no results help me please

**Comment by AhmedAdelAtta** [comment]
> @mkloubert i think i'm missing some steps.
> Why it works correctly setting up a web application clientId and it's not working (return code: 1) with android client id, without setting up a secret?
> I am confused

is it working for you for android google login?? i keep getting code 1

**Comment by odedBartov** [comment]
is this thread still open? i have exactly the same problem. i recieve  from the server
{
"provider": "google",
  "code": 1
}. i have a web application id for serverClientId and the client id for clientId

**Comment by oded-bartov** [comment]
> > @mkloubert i think i'm missing some steps.
> > Why it works correctly setting up a web application clientId and it's not working (return code: 1) with android client id, without setting up a secret?
> > I am confused
> 
> is it working for you for android google login?? i keep getting code 1

did you had any success?

**Comment by dereekb** [comment]
Going to preface this with saying my app retrieves an Auth Code that I send to my server for authentication, so this might not be applicable to those who have a backend that trades the Auth Code for an Authorization Token.

I ran into this issue a while back, and spent a lot of time debugging it. It turned out to be a configuration issue with my project's OAuth on Google and not within the app at all.

Here's what the key I used for login looked like:

![Screen Shot 2020-11-02 at 12 03 22 PM](https://user-images.githubusercontent.com/3586580/97902837-c3ae0080-1d03-11eb-8165-28e44de87fe5.png)

and configuration:

![Screen Shot 2020-11-02 at 12 03 35 PM](https://user-images.githubusercontent.com/3586580/97902809-b5f87b00-1d03-11eb-82e2-a5d143f4cc86.png)

I tried for a long time to use an OAuth 2.0 Client ID configured to Android and eventually came across the documentation that said not to do that, and instead configure your Client ID for Web application, and to not use the Android.

That said, while typing this I remembered that I ended up using [nativescript-google-login](https://github.com/pboulch/nativescript-google-login) by the end instead, I think because I could get the Auth Code back and send it to the server.

Here's what my configuration for initializing that plugin looked like from my login component:

```
private _initGoogleLogin() {
        const config: Partial<IConfig> = {
            activity: undefined,
            viewController: undefined,
            google: {
                clientId: undefined,
                serverClientId: environment.googleServerClientId,
                isRequestAuthCode: true    // Get the Auth Code
                // scopes: ['email', 'profile', 'openid']
            },
            onActivityResult: undefined
        };

        const google = config.google;

        if (isIOS) {
            google.clientId = environment.iosGoogleClientId;
            config.viewController = application.ios.rootController;
        } else {
            // Only set the serverClientId.
            config.activity = application.android.foregroundActivity;
        }

        GoogleLogin.init(config);
    }
```

Debugging OAuth issues is the worst, so I hope this helps you.

**Comment by odedBartov** [comment]
i did exatly like you ->
created OAuth 2.0 Client IDs of type web on google platform.
this is the code on my client:
```
 GoogleLogin.init({
            viewController: undefined,
            activity: undefined,
            google: {
                initialize: true,
                serverClientId: "the client id of the web oauth.apps.googleusercontent.com",
                clientId: undefined,
                isRequestAuthCode: true
            },
        })
```
when i call to GoogleLogin.login() i get this:
```
{
   "provider": "google",
   "code": 1
 }
```
